server:
  port: ${PORT:8081}

spring:
  application:
    name: MS-BOOKS-CATALOGUE
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

opensearch:
  url: ${OPENSEARCH_URL:}
  username: ${OPENSEARCH_USERNAME:}
  password: ${OPENSEARCH_PASSWORD:}
  index: ${OPENSEARCH_INDEX:relatos}
  recreate-on-incompatible-mapping: ${OPENSEARCH_RECREATE_ON_INCOMPATIBLE_MAPPING:false}

eureka:
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${server.port}
  client:
    enabled: ${EUREKA_ENABLED:true}
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
