server:
  port: ${PORT:8082}

spring:
  application:
    name: MS-BOOKS-PAYMENTS

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:payments_db}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:payments_user}
    password: ${POSTGRES_PASSWORD:payments_pass}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    show-sql: ${JPA_SHOW_SQL:true}
    defer-datasource-initialization: true

  sql:
    init:
      mode: ${SQL_INIT_MODE:always}

eureka:
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${server.port}
  client:
    enabled: ${EUREKA_ENABLED:true}
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
