server:
  port: 8082 #Puerto del microservicio

spring:
  application:
    name: MS-BOOKS-PAYMENTS #Nombre del microservicio

  datasource:
    url: jdbc:h2:mem:payments_db #Nombre de la base de datos
    driver-class-name: org.h2.Driver #Driver de la base de datos
    username: sa #Usuario de la base de datos
    password: "" #Password de la base de datos

  jpa:
    hibernate:
      ddl-auto: create-drop #Creacion de tablas al iniciar y eliminacion al finalizar
    show-sql: true #Muestra queries SQL en consola
    defer-datasource-initialization: true #Inicializacion de la base de datos

  h2:
    console:
      enabled: true #Habilita la consola de H2
      path: /h2-console #Ruta de la consola de H2

eureka:
  instance:
    preferIpAddress: false #Registro por nombre
    hostname: localhost #Nombre del host
    instance-id: ${spring.application.name}:${server.port} #ID personalizado de la instancia
  client:
    register-with-eureka: true #Registro con Eureka como cliente
    fetch-registry: true #Obtencion de registros de otros microservicios
    service-url:
      defaultZone: http://localhost:8761/eureka #URL del servidor Eureka
