server:
  port: ${PORT:8762}

## Classic Eureka configuration
eureka:
  instance:
    preferIpAddress: false # hostname en lugar de IP
    hostname: ${HOSTNAME:localhost} # hostname
    instance-id: ${spring.application.name}:${server.port} # nombre del servicio + puerto

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

## Enable service discovery (with Eureka)
## lower-case-service-id is mandatory, otherwise is retrieved in upper case from Eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Ruta explícita para MS Books Catalogue
            - id: ms-books-catalogue
              uri: lb://MS-BOOKS-CATALOGUE
              predicates:
                - Path=/api/books/**
            # Ruta explícita para MS Books Payments
            - id: ms-books-payments
              uri: lb://MS-BOOKS-PAYMENTS
              predicates:
                - Path=/api/payments/**
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS

## We enable the Actuator API to be able to access <<host>>/actuator/gateway/routes
## We expose the routings that have been automatically detected (all)
## Depending on the ROUTE_TABLES_ENABLED environment variable (true by default)
management:
  endpoint:
    gateway:
      access: ${ROUTE_TABLES_ENABLED:read_only}
  endpoints:
    web:
      exposure:
        include:
          - "*"
