server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: false #No se registra en el eureka server
    fetch-registry: false #No se busca en el eureka server
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
